name: Action1
description: Action1 for the main runner

inputs:
  var1:
    default: "Minato Namikaze"
    required: false

  var2:
    default: "Kushina Uzumaki"
    required: false

runs:
  using: "composite"
  steps:
    - name: Ifconfig
      shell: bash
      run: ifconfig
      
    - name: Echoing the var1 content...
      shell: bash
      run: echo ${{ inputs.var1 }}

    - name: Echoing the var2 content...
      shell: bash
      run: echo ${{ inputs.var2 }}
      
