name: Action1
description: Action1 for the main runner

inputs:
  var1:
    default: "Naruto Uzumaki"
    required: false

  var2:
    default: "Hinata Hyuga"
    required: false

outputs:
  output1:
    required: true

runs:
  using: "composite"
  
  steps:
    - name: Echoing the var1 content...
      shell: bash  
      run: echo ${{ inputs.var1 }}

    - name: Echoing the var2 content...
      shell: bash
      var2: "Well done"
      run: echo ${{ inputs.var2 }}
      
      
