name: Action1
description: Action1 for the main runner

inputs:
  var1:
    default: "Naruto Uzumaki"
    required: false

  var2:
    default: "Hinata Hyuga"
    required: false

outputs:
  output1:
    required: true

env:
    variable1: ${{ inputs.var1 }}
    variable2: ${{ inputs.var2 }}
    
runs:
  using: "composite"
  
    
  steps:
    - name: Echoing the var1 content...
      shell: bash  
      run: |
        echo ${{ inputs.var1 }}
        echo ${{ env.variable1 }}

    - name: Echoing the var2 content...
      shell: bash
      env.var2: "Well done"
      run: |
        echo ${{ inputs.var2 }}
        echo ${{ env.variable2 }}
      
      
      
