name: Action1
description: Action1 for the main runner

input:
  var1:
    default: "Naruto Uzumaki"
    required: false

  var2:
    default: "Hinata Hyuga"
    required: false

runs:
  using: "composite"
  shell: bash
  steps:
    - name: Echoing the var1 content...
      run: echo ${{ inputs.var1 }}

    - name: Echoing the var2 content...
      run: echo ${{ inputs.var2 }}
      
