name: Main runner

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Echoing the Start...
      run: echo "Started the main runner"

    - name: Checking out the repo...
      uses: actions/checkout@v3
      
    - name: Using the Action1...
      uses: ./.github/actions/action1

    - name: Using the Action2...
      uses: ./.github/actions/action2
      with:
        var1: "Sukumaran Minato"
      
